spring:
  data:
    redis:
      host: redis-shzl6tz4l7lst4rga.redis.volces.com
      port: 6379
      password: QWer1234!!!   # 没密码可不写
      database: 3

  datasource:
    url: jdbc:mysql://mysql-02a756b9c0e4-public.rds.volces.com:3306/yanque-shiyi?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: QWer1234!!!

logging:
  level:
    cn.yqnaue: INFO

yeepay:
  pay-success-notify-url: "http://10ro09314qm96.vicp.fun:8878/yq-admin/yop-callback/paySuccess"
  pay-success-return-url: "http://127.0.0.1:5174/payment-return"